task: itabench_discotex_p6

description: "Indica la frase che rappresenta la continuazione più probabile del paragrafo, oppure \"nessuna delle precedenti\" se nessuna delle continuazioni è corretta."

doc_to_text: "Paragrafo: \"{{text}}\"\nContinuazioni\n-. \"{{choices[0]}}\"\n-. \"{{choices[1]}}\"\n-. \"{{choices[2]}}\"\n-. \"{{choices[3]}}\"\n-. {{choices[4]}}\nTra le precedenti frasi la continuazione del paragrafo è:"
doc_to_target: label
doc_to_choice: choices