task: itabench_quandho_mc
dataset_path: sapienzanlp/quandho
output_type: multiple_choice

description: "Ti saranno poste domande di storia italiana.\nIdentifica quali paragrafi contengono la risposta alle domande date.\n\n"

training_split: train
validation_split: train
test_split: test

doc_to_text: "Data la domanda: \"{{question}}\"\nQuale tra i seguenti paragrafi risponde alla domanda?\nA. {{choices[0]}}\nB. {{choices[1]}}\nC. {{choices[2]}}\nD. {{choices[3]}}\nRisposta:"
doc_to_target: label
doc_to_choice: ["A", "B", "C", "D"]

metric_list:
  - metric: acc
    aggregation: mean 
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true

metadata:
  version: 1.0