include: _ami_behaviour_yaml
task: itabench_ami_behaviour_p3

doc_to_text: "Quale è il livello di misoginia presenten nel seguente tweet '{{text}}'?\nA. Nessuno\nB. Misogino\nC. Misogino aggressivo\nRisposta:"
doc_to_target: label
doc_to_choice: ["A", "B", "C"]