include: _ghigliottinai_yaml

task: itabench_ghigliottinai_p5

doc_to_text: "Date le parole: {{w1}}, {{w2}}, {{w3}}, {{w4}}, {{w5}}\nIl concetto che lega le parole date è:"
doc_to_target: label
doc_to_choice: choices
