group: itabench_adapt_cloze

task:
  - task: itabench_ami_cloze
  - task: itabench_ghigliottinai_cloze
  - task: itabench_nermud_cloze
  - task: itabench_plearn_cloze
  - task: itabench_pretens_cloze
  - task: itabench_wic_cloze