include: _wic_yaml

task: itabench_wic_p3

doc_to_text: "Frase 1: {{sentence1}}\nFrase 2: {{sentence2}}\nDomanda: La parola \"{{lemma}}\" ha lo stesso signicato nelle due frasi precedenti?\nA. no\nB. sì\nRisposta:"
doc_to_target: label
doc_to_choice: ["A", "B"]