include: ../_ami_behaviour_yaml
task: itabench_ami_behaviour_mc
dataset_name: Behaviour
doc_to_text: "Tweet: '{{text}}'.\nDomanda: che livello di misoginia è presente nel tweet?\nA. Nessuno\nB. Misogino\nC. Misogino aggressivo\nRisposta:"
doc_to_target: label
doc_to_choice: ["A", "B", "C"]
