include: _quandho_yaml
task: itabench_quandho_p6

doc_to_text: "Dovrai rispondere in maniera dettagliata a domande di storia italiana.\nData la domanda: \"{{question}}\"\nIl seguente paragrafo risponde alla domanda data:"
doc_to_target: label
doc_to_choice: "{{choices}}"