include: _nermud_wn_yaml

task: itabench_nermud_wn_p3

doc_to_text: "Data la frase: \"{{text}}\"\nDomanda: A quale tipologia di entità appartiene \"{{target_entity}}\" nella frase precedente?\nA. Luogo\nB. Organizzazione\nC. Persona\nRisposta:"
doc_to_target: label
doc_to_choice: ["A", "B", "C"]
